Added support for runtime analysis and add input to test results
beatcode-official/beatcode-server pull request #13
Opened 2024-12-08 15:34 UTC by hdngo

For now, runtime analysis only happens when all test cases are cleared since I don't wanna make unneeded API calls with errored code for example. Let me know if you want this adjusted.

Based on testing with the TA seems like showing the input for tests is more intuitive for the users so we'll go along with that.

2024-12-09 00:32 UTC, hdngo commented
Actually, I'll just include input for sample test cases only, wait for next commit.

Also another note, perhaps a pop up showing their runtime after all test cases a solved would be a way to display this.

2024-12-09 16:43 UTC, weebao requested changes
Use `response_format` for OpenAI `chat.completions.create` function. Check the inline code review comment for more details

2024-12-09 17:04 UTC, hdngo commented on app/services/execution/runtime_analysis.py
> +                temperature=0
Thanks, I didn't know about that, please check the latest commit [130ba87](https://github.com/beatcode-official/beatcode-server/pull/13/commits/130ba87cecc1617b268db8a999db2a0ca4f560d9) 🙂

2024-12-10 01:01 UTC, weebao approved these changes
Looks good now

2024-12-10 01:01 UTC, merged

2024-12-10 23:15 UTC, weebao commented
Closes #12